# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr:
  branches:
    include:
    - '*'

pool:
  name: SOGEI-CLOUD

steps:
- script: ls -l
  displayName: 'Run a one-line script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'pull-request-files'
    publishLocation: 'pipeline'
